name: Deploy to EC2
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-2
    steps:
      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Add Github Actions IP to Security Group
        run: aws ec2 authorize-security-group-ingress --group-name launch-wizard-4 --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Jar File
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
      - name: Release Server Jar
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: ./build/libs/*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_SSH_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: 22
          script: |
            url=$(curl https://api.github.com/repos/ldhdev916/UtilityServer/releases/latest | jq ".assets[0] | .browser_download_url" | tr -d '"')
            wget $url -O Server.jar
            sudo kill -9 $(pidof java) 2> /dev/null
      - name: Remove Github Actions IP from Security Group
        run: aws ec2 revoke-security-group-ingress --group-name launch-wizard-4 --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32